name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Generate GitHub App token
      id: app-token
      uses: peter-evans/create-github-app-token@v2
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Close PR using App Token
      uses: zunalita-admin/close-pull-request@v1
      with:
        github_token: ${{ steps.app-token.outputs.token }}

        comment: "This is a read-only repo for discussions related to the Zunalita Blog, your pull request has been closed."
